/* SPDX-License-Identifier: MIT */
#pragma once

/* Authoritative 280x240 logical layout. All rectangles use [x,x+w) × [y,y+h). */
enum {
  NC_REGION_HEADER=1, NC_REGION_SCENE=2, NC_REGION_STATUS=4, NC_REGION_FOOTER=8,
  NC_REGION_ALL=15,
  NC_CANVAS_W=280, NC_CANVAS_H=240,
  NC_HEADER_Y=0, NC_HEADER_H=49,
  NC_SCENE_X=0, NC_SCENE_Y=49, NC_SCENE_W=280, NC_SCENE_H=102,
  NC_STATUS_Y=151, NC_STATUS_H=47,
  NC_FOOTER_Y=198, NC_FOOTER_H=42,

  NC_BLE_ICON_X=12, NC_BLE_ICON_Y=13, NC_BLE_ICON_W=21, NC_BLE_ICON_H=32,
  NC_BLE_TEXT_X=41, NC_BLE_TEXT_Y=15, NC_BLE_TEXT_W=29, NC_BLE_TEXT_H=13,
  NC_PROFILE_X=42, NC_PROFILE_Y=32, NC_PROFILE_W=20, NC_PROFILE_H=14,
  NC_LAYER_LABEL_X=88, NC_LAYER_LABEL_Y=10, NC_LAYER_LABEL_W=100, NC_LAYER_LABEL_H=14,
  NC_LAYER_X=87, NC_LAYER_Y=24, NC_LAYER_W=109, NC_LAYER_H=35,
  NC_TOP_BATTERY_X=221, NC_TOP_BATTERY_Y=11, NC_TOP_BATTERY_W=44, NC_TOP_BATTERY_H=20,
  NC_TOP_PERCENT_X=230, NC_TOP_PERCENT_Y=34, NC_TOP_PERCENT_W=34, NC_TOP_PERCENT_H=14,

  NC_CAT_X=163, NC_CAT_Y=87, NC_CAT_W=85, NC_CAT_H=64,
  NC_HEART_X=229, NC_HEART_Y=97, NC_HEART_W=27, NC_HEART_H=27,

  NC_LEFT_STATUS_X=17, NC_LEFT_STATUS_Y=154, NC_LEFT_STATUS_W=60, NC_LEFT_STATUS_H=38,
  NC_LEFT_BATTERY_X=16, NC_LEFT_BATTERY_Y=171, NC_LEFT_BATTERY_W=60, NC_LEFT_BATTERY_H=20,
  NC_WPM_PANEL_X=90, NC_WPM_PANEL_Y=154, NC_WPM_PANEL_W=100, NC_WPM_PANEL_H=40,
  NC_WPM_LABEL_X=126, NC_WPM_LABEL_Y=158, NC_WPM_LABEL_W=31, NC_WPM_LABEL_H=10,
  NC_WPM_VALUE_X=122, NC_WPM_VALUE_Y=169, NC_WPM_VALUE_W=38, NC_WPM_VALUE_H=22,
  NC_WPM_FONT_Y=154, NC_WPM_FONT_VISIBLE_TOP=156, NC_WPM_FONT_VISIBLE_BOTTOM=166,
  NC_WPM_DIGITS_Y=169, NC_WPM_DIGITS_VISIBLE_TOP=171, NC_WPM_DIGITS_VISIBLE_BOTTOM=187,
  NC_EQ_LEFT_X=94, NC_EQ_LEFT_Y=174, NC_EQ_LEFT_W=22, NC_EQ_LEFT_H=17,
  NC_EQ_RIGHT_X=164, NC_EQ_RIGHT_Y=174, NC_EQ_RIGHT_W=22, NC_EQ_RIGHT_H=17,
  NC_RIGHT_STATUS_X=202, NC_RIGHT_STATUS_Y=154, NC_RIGHT_STATUS_W=61, NC_RIGHT_STATUS_H=38,
  NC_RIGHT_BATTERY_X=205, NC_RIGHT_BATTERY_Y=171, NC_RIGHT_BATTERY_W=60, NC_RIGHT_BATTERY_H=20,

  NC_CTRL_X=13, NC_CTRL_Y=206, NC_CTRL_W=34, NC_CTRL_H=22,
  /* ALT's nominal slot is one pixel down/right; raised state lands at 54,206. */
  NC_ALT_X=55, NC_ALT_Y=207, NC_ALT_W=33, NC_ALT_H=22,
  NC_LOGO_X=105, NC_LOGO_Y=204, NC_LOGO_W=72, NC_LOGO_H=26,
  NC_GUI_X=193, NC_GUI_Y=206, NC_GUI_W=33, NC_GUI_H=22,
  NC_SHIFT_X=233, NC_SHIFT_Y=206, NC_SHIFT_W=34, NC_SHIFT_H=22,

  NC_FONT_CELL_W=27, NC_FONT_CELL_H=34, NC_FONT_ADVANCE=27,
  NC_FONT_GLYPH_MAX_W=24, NC_FONT_GLYPH_MAX_H=31,
  NC_LAYER_MAX_W=112,

  NC_BATTERY_FILL_X=5, NC_BATTERY_FILL_Y=5,
  NC_BATTERY_FILL_W=47, NC_BATTERY_FILL_H=11,
  NC_TOP_FILL_X=5, NC_TOP_FILL_Y=5,
  NC_TOP_FILL_W=31, NC_TOP_FILL_H=11
};

_Static_assert(NC_SCENE_Y+NC_SCENE_H==NC_STATUS_Y,"scene/status boundary");
_Static_assert(NC_STATUS_Y+NC_STATUS_H==NC_FOOTER_Y,"status/footer boundary");
_Static_assert(NC_FOOTER_Y+NC_FOOTER_H==NC_CANVAS_H,"footer/canvas boundary");
_Static_assert(NC_LEFT_STATUS_X+NC_LEFT_STATUS_W<NC_WPM_PANEL_X,"left/WPM gap");
_Static_assert(NC_WPM_PANEL_X+NC_WPM_PANEL_W<NC_RIGHT_STATUS_X,"WPM/right gap");
_Static_assert(NC_WPM_FONT_VISIBLE_TOP>NC_WPM_PANEL_Y,"WPM label clears top border");
_Static_assert(NC_WPM_FONT_VISIBLE_BOTTOM<NC_WPM_DIGITS_VISIBLE_TOP,"WPM label/value gap");
_Static_assert(NC_WPM_DIGITS_VISIBLE_BOTTOM<NC_WPM_PANEL_Y+NC_WPM_PANEL_H-1,"WPM value clears bottom border");
_Static_assert(NC_ALT_X+NC_ALT_W<NC_LOGO_X,"left buttons/logo gap");
_Static_assert(NC_LOGO_X+NC_LOGO_W<NC_GUI_X,"logo/right buttons gap");
