#!/usr/bin/env python3
"""Generate immutable fixed-point geometry and phosphor tables for radar-scan."""

from __future__ import annotations

import argparse
import hashlib
import math
from pathlib import Path

SIDE = 101
STEP_MS = 8
TRAIL_MS = 1667


def values(items: list[int], width: int = 16) -> str:
    rows = []
    for start in range(0, len(items), width):
        rows.append("    " + ", ".join(str(value) for value in items[start : start + width]) + ",")
    return "\n".join(rows)


def rgb565(red: int, green: int, blue: int) -> int:
    return ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)


def color(level: int) -> int:
    x = level / 255.0
    if x <= 0:
        return 0
    if x < 0.34:
        u = x / 0.34
        red, green, blue = 3 + 5 * u, 20 + 102 * u, 18 + 70 * u
    elif x < 0.76:
        u = (x - 0.34) / 0.42
        red, green, blue = 8 + 39 * u, 122 + 118 * u, 88 + 43 * u
    else:
        u = (x - 0.76) / 0.24
        red, green, blue = 47 + 168 * u, 240 + 15 * u, 131 + 104 * u
    return rgb565(round(red), round(green), round(blue))


def main(output: Path) -> None:
    angles: list[int] = []
    radii: list[int] = []
    for y in range(SIDE):
        for x in range(SIDE):
            angles.append(round(math.degrees(math.atan2(x, y)) * 10) if x or y else 0)
            radii.append(min(255, round(math.hypot(x, y))))

    fast: list[int] = []
    slow: list[int] = []
    for elapsed in range(0, TRAIL_MS + STEP_MS, STEP_MS):
        taper_start = 1300
        if elapsed <= taper_start:
            taper = 1.0
        else:
            u = min(1.0, (elapsed - taper_start) / (TRAIL_MS - taper_start))
            taper = 1.0 - u * u * (3.0 - 2.0 * u)
        seconds = elapsed / 1000.0
        fast.append(round(255 * 0.72 * 2 ** (-seconds / 0.10) * taper))
        slow.append(round(255 * 0.28 * 2 ** (-seconds / 0.65) * taper))

    colors = [color(level) for level in range(256)]
    body = f"""/* Generated by scripts/generate_radar_luts.py; do not edit. */
#pragma once
#include <stdint.h>

#define ZDSE_RADAR_LUT_SIDE {SIDE}
#define ZDSE_RADAR_PHOSPHOR_STEP_MS {STEP_MS}
#define ZDSE_RADAR_PHOSPHOR_TRAIL_MS {TRAIL_MS}
#define ZDSE_RADAR_PHOSPHOR_SAMPLES {len(fast)}

static const uint16_t zdse_radar_quadrant_angle10[{len(angles)}] = {{
{values(angles)}
}};

static const uint8_t zdse_radar_quadrant_radius[{len(radii)}] = {{
{values(radii)}
}};

static const uint8_t zdse_radar_phosphor_fast[{len(fast)}] = {{
{values(fast)}
}};

static const uint8_t zdse_radar_phosphor_slow[{len(slow)}] = {{
{values(slow)}
}};

static const uint16_t zdse_radar_phosphor_rgb565[256] = {{
{values(colors)}
}};
"""
    digest = hashlib.sha256(body.encode()).hexdigest()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(body + f"\n/* content-sha256: {digest} */\n")
    print(f"{output}: {digest}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    main(parser.parse_args().output)
